// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"67cea935bdb79d09d78c84718a970b077df833a540c40c80287b450cd9eb9840e5c195fb4318ed44d0eee4db746f93dfd252f913a4747a2cc1fef6108196e1ef"}}
];
